# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_med2 <- function(xx) {
    .Call(`_SNSeg_cpp_med2`, xx)
}

cpp_quantile <- function(xx, q) {
    .Call(`_SNSeg_cpp_quantile`, xx, q)
}

cpp_cumquantile <- function(xx, q) {
    .Call(`_SNSeg_cpp_cumquantile`, xx, q)
}

cumsum_median_constrast_Cpp <- function(ts, type) {
    .Call(`_SNSeg_cumsum_median_constrast_Cpp`, ts, type)
}

cumsum_quantile_constrast_Cpp_check <- function(ts, type, q) {
    .Call(`_SNSeg_cumsum_quantile_constrast_Cpp_check`, ts, type, q)
}

cumsum_quantile_constrast_Cpp <- function(ts, type, q) {
    .Call(`_SNSeg_cumsum_quantile_constrast_Cpp`, ts, type, q)
}

cpp_acf <- function(ts) {
    .Call(`_SNSeg_cpp_acf`, ts)
}

cumsum_acf_constrast_Cpp <- function(ts, type) {
    .Call(`_SNSeg_cumsum_acf_constrast_Cpp`, ts, type)
}

